---
abstract: 'simple stateless slideshow with a fixed set of images'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Slideshow
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008
  strict: 0
resources:
  repository: http://github.com/Corion/time-slideshow
version: 0.01
